#!/usr/bin/env bash
# Loops 1-10, custom text on 4th, 8th, and other iterations 

count=1
while [ $count -le 10 ]
do
  if [ $count -eq 4 ]
  then
    echo "bad luck" 
  elif [ $count -eq 8 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi

  ((count++))
done