#!/usr/bin/env bash
# Displays 1-20 with custom text on 4th, 9th and 17th iterations

count=1
while [ $count -le 20 ]
do
  case $count in
     4)
        echo "$count"
        echo "bad luck from China" ;;
     9) 
        echo "$count" 
        echo "bad luck from Japan" ;;
     17)
        echo "$count"
        echo "bad luck from Italy" ;;  
     *)
        echo "$count" ;;
  esac

  ((count++))
done